# Generated by Django 4.2.8 on 2024-03-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('bitpin', '0001_initial'), ('bitpin', '0002_remove_bitpincurrency_network_id_and_more'), ('bitpin', '0003_alter_bitpincurrency_price_info_time_and_more'), ('bitpin', '0004_bitpincurrency_active')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitPinNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('title_fa', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BitPinCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_fa', models.CharField(blank=True, max_length=255, verbose_name='Title (فارسی)')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('image', models.URLField(verbose_name='Image URL')),
                ('min_withdraw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Withdrawal')),
                ('color', models.CharField(max_length=6, verbose_name='Color')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Alias')),
                ('withdraw_commission', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Withdrawal Commission')),
                ('withdraw_commission_type', models.CharField(max_length=10, verbose_name='Withdrawal Commission Type')),
                ('max_withdraw_commission', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Maximum Withdrawal Commission')),
                ('tradable', models.BooleanField(verbose_name='Tradable')),
                ('for_test', models.BooleanField(verbose_name='For Test')),
                ('decimal', models.IntegerField(verbose_name='Decimal Places')),
                ('decimal_amount', models.IntegerField(verbose_name='Decimal Amount')),
                ('decimal_irt', models.IntegerField(verbose_name='Decimal (IRT)')),
                ('high_risk', models.BooleanField(verbose_name='High Risk')),
                ('show_high_risk', models.BooleanField(verbose_name='Show High Risk')),
                ('recommend_for_deposit_weight', models.IntegerField(verbose_name='Recommend for Deposit Weight')),
                ('for_loan', models.BooleanField(verbose_name='For Loan')),
                ('for_stake', models.BooleanField(verbose_name='For Stake')),
                ('price_info_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Price')),
                ('price_info_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان')),
                ('price_info_change', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='تغییر')),
                ('price_info_min', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Minimum')),
                ('price_info_max', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Maximum')),
                ('price_info_mean', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Mean')),
                ('price_info_value', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Market Value')),
                ('price_info_amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Market Amount')),
                ('price_info_market_value', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Total Market Value')),
                ('price_info_market_amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Total Market Amount')),
                ('price_info_usdt_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Price USDT')),
                ('price_info_usdt_time', models.DateTimeField(blank=True, null=True, verbose_name='Time USDT')),
                ('price_info_usdt_change', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Change USDT')),
                ('price_info_usdt_min', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Minimum USDT')),
                ('price_info_usdt_max', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Maximum USDT')),
                ('price_info_usdt_mean', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Mean USDT')),
                ('price_info_usdt_value', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Market Value USDT')),
                ('price_info_usdt_amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Market Amount USDT')),
                ('price_info_usdt_market_value', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Total Market Value USDT')),
                ('price_info_usdt_market_amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Total Market Amount USDT')),
                ('network_ids', models.ManyToManyField(blank=True, to='bitpin.bitpinnetwork')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
