# Generated by Django 4.2.8 on 2024-04-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0006_alter_bitpincurrency_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Market Amount'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_change',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='تغییر'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_market_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Total Market Amount'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_market_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Total Market Value'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_max',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Maximum'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_mean',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Mean'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_min',
            field=models.DecimalField(decimal_places=8, default='0', max_digits=20, verbose_name='Minimum'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Market Amount USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_change',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Change USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_market_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Total Market Amount USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_market_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Total Market Value USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_max',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Maximum USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_mean',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Mean USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_min',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Minimum USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Price USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Market Value USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Market Value'),
        ),
    ]
