# Generated by Django 4.2.8 on 2024-04-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0008_alter_bitpincurrency_price_info_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitpincurrency',
            name='withdraw_commission',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Withdrawal Commission'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='withdraw_commission_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Withdrawal Commission Type'),
        ),
    ]
