# Generated by Django 4.2.8 on 2024-04-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0009_alter_bitpincurrency_withdraw_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitpincurrency',
            name='decimal',
            field=models.IntegerField(default=0, verbose_name='Decimal Places'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='decimal_amount',
            field=models.IntegerField(default=0, verbose_name='Decimal Amount'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='for_loan',
            field=models.BooleanField(default=False, verbose_name='For Loan'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='for_stake',
            field=models.BooleanField(default=False, verbose_name='For Stake'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='for_test',
            field=models.BooleanField(default=False, verbose_name='For Test'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='high_risk',
            field=models.BooleanField(default=False, verbose_name='High Risk'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='min_withdraw',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Minimum Withdrawal'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='show_high_risk',
            field=models.BooleanField(default=False, verbose_name='Show High Risk'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='tradable',
            field=models.BooleanField(default=False, verbose_name='Tradable'),
        ),
    ]
