# Generated by Django 4.2.8 on 2024-04-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0010_alter_bitpincurrency_decimal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitpincurrency',
            name='max_withdraw_commission',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Withdrawal Commission'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='min_withdraw',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Withdrawal'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Market Amount'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_change',
            field=models.FloatField(blank=True, null=True, verbose_name='تغییر'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_market_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Market Amount'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_market_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Market Value'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_mean',
            field=models.FloatField(blank=True, null=True, verbose_name='Mean'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Market Amount USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_change',
            field=models.FloatField(blank=True, null=True, verbose_name='Change USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_market_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Market Amount USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_market_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Market Value USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_mean',
            field=models.FloatField(blank=True, null=True, verbose_name='Mean USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Market Value USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Market Value'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='withdraw_commission',
            field=models.FloatField(blank=True, null=True, verbose_name='Withdrawal Commission'),
        ),
    ]
