# Generated by Django 4.2.11 on 2024-04-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0011_alter_bitpincurrency_max_withdraw_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitpincurrency',
            name='show_in_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
