# Generated by Django 4.2.11 on 2024-04-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0012_bitpincurrency_show_in_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitPinWalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitpin.bitpincurrency', verbose_name='Currency')),
                ('network_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitpin.bitpinnetwork', verbose_name='Network')),
            ],
            options={
                'verbose_name': 'BitPin Wallet Address',
                'verbose_name_plural': 'BitPin Wallet Addresses',
            },
        ),
    ]
