# Generated by Django 4.2.11 on 2024-04-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0013_bitpinwalletaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitpincurrency',
            options={'ordering': ('-show_in_dashboard', '-price_info_price'), 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
