# Generated by Django 4.2.11 on 2024-04-09 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0014_alter_bitpincurrency_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitpincurrency',
            options={'ordering': ('-show_in_dashboard', '-price_info_price'), 'verbose_name': 'ارز', 'verbose_name_plural': 'ارزها'},
        ),
        migrations.AlterModelOptions(
            name='bitpinnetwork',
            options={'verbose_name': 'شبکه', 'verbose_name_plural': 'شبکه ها'},
        ),
        migrations.AlterModelOptions(
            name='bitpinwalletaddress',
            options={'verbose_name': 'آدرس کیف پول', 'verbose_name_plural': 'آدرس کیف پول ها'},
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال(بیت پین)'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='alias',
            field=models.CharField(blank=True, max_length=255, verbose_name='مستعار'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='bitasia_active',
            field=models.BooleanField(default=True, verbose_name='فعال (بیت آسیا)'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='code',
            field=models.CharField(max_length=10, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='color',
            field=models.CharField(max_length=6, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='decimal',
            field=models.IntegerField(default=0, verbose_name='رقم اعشار'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='decimal_amount',
            field=models.IntegerField(default=0, verbose_name='تعداد ارقام'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='decimal_irt',
            field=models.IntegerField(verbose_name='اعشار در تومان'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='for_loan',
            field=models.BooleanField(default=False, verbose_name='برای وام'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='for_test',
            field=models.BooleanField(default=False, verbose_name='برای تست'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='high_risk',
            field=models.BooleanField(default=False, verbose_name='ریسک بالا'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='آذرس تصویر'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='max_withdraw_commission',
            field=models.FloatField(blank=True, null=True, verbose_name='حداکثر کارمزد برداشت'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='min_withdraw',
            field=models.FloatField(blank=True, null=True, verbose_name='حداقل برداشت'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='مقدار بازار'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_market_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='مقدار کل بازار'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_market_value',
            field=models.FloatField(blank=True, null=True, verbose_name='ارزش کل بازار'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_max',
            field=models.FloatField(blank=True, null=True, verbose_name='حداکثر'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_mean',
            field=models.FloatField(blank=True, null=True, verbose_name='میانگین'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_min',
            field=models.FloatField(blank=True, null=True, verbose_name='حداقل'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت تومانی'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_value',
            field=models.FloatField(blank=True, null=True, verbose_name='ارزش بازار'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='recommend_for_deposit_weight',
            field=models.IntegerField(verbose_name='توصیه برای وزن واریز'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='show_high_risk',
            field=models.BooleanField(default=False, verbose_name='نمایش ریسک بالا'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='title_fa',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان فارسی'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='tradable',
            field=models.BooleanField(default=False, verbose_name='قابل معامله'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='withdraw_commission',
            field=models.FloatField(blank=True, null=True, verbose_name='کارمزد برداشت'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='withdraw_commission_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='نوع کارمزد برداشت'),
        ),
        migrations.AlterField(
            model_name='bitpinwalletaddress',
            name='address',
            field=models.CharField(max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='bitpinwalletaddress',
            name='currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitpin.bitpincurrency', verbose_name='ارز'),
        ),
        migrations.AlterField(
            model_name='bitpinwalletaddress',
            name='network_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitpin.bitpinnetwork', verbose_name='شبکه'),
        ),
    ]
