# Generated by Django 4.2.11 on 2024-04-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0015_alter_bitpincurrency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitpincurrency',
            name='markup_percent',
            field=models.FloatField(default=0, verbose_name='Sales Markup Percent'),
        ),
        migrations.AddField(
            model_name='bitpincurrency',
            name='price',
            field=models.FloatField(default=0, verbose_name='Sales Price'),
        ),
    ]
