# Generated by Django 4.2.11 on 2024-04-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0016_bitpincurrency_markup_percent_bitpincurrency_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitpincurrency',
            name='markup_percent',
            field=models.DecimalField(decimal_places=5, default=0.001, max_digits=10, verbose_name='Sales Markup Percent'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='max_withdraw_commission',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=24, null=True, verbose_name='حداکثر کارمزد برداشت'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='min_withdraw',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=24, null=True, verbose_name='حداقل برداشت'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=24, verbose_name='Sales Price'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_amount',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='مقدار بازار'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_change',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='تغییر'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_market_amount',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='مقدار کل بازار'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_market_value',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='ارزش کل بازار'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_max',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='حداکثر'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_mean',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='میانگین'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_min',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='حداقل'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_price',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='قیمت تومانی'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_amount',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='Market Amount USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_change',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='Change USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_market_amount',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='Total Market Amount USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_market_value',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='Total Market Value USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_max',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='Maximum USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_mean',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='Mean USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_min',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='Minimum USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_price',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='Price USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_usdt_value',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='Market Value USDT'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='price_info_value',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=24, verbose_name='ارزش بازار'),
        ),
        migrations.AlterField(
            model_name='bitpincurrency',
            name='withdraw_commission',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=24, null=True, verbose_name='کارمزد برداشت'),
        ),
    ]
