# Generated by Django 4.2.11 on 2024-04-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0018_bitpincurrency_buy_sell_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitpincurrency',
            name='price_usdt',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=24, verbose_name='Sales USDT Price'),
        ),
    ]
