# Generated by Django 4.2.11 on 2024-04-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'verbose_name': 'کارت اعتباری', 'verbose_name_plural': 'کارتهای اعتباری'},
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(max_length=16, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='iban',
            field=models.CharField(max_length=26, verbose_name='شبا'),
        ),
    ]
