# Generated by Django 4.2.8 on 2024-01-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
