# Generated by Django 4.2.8 on 2024-01-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_birthdate_customuser_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
