# Generated by Django 4.2.11 on 2024-04-16 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('successful', models.BooleanField(default=False)),
                ('ip', models.CharField(default='0.0.0.0', max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login history',
                'verbose_name_plural': 'Login histories',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
