# Generated by Django 4.2.11 on 2024-04-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_loginhistory'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='loginhistory',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='reason',
            field=models.CharField(blank=True, choices=[('invalid_otp', 'Invalid OTP'), ('invalid_password', 'Invalid Password')], max_length=16, null=True),
        ),
    ]
