# Generated by Django 4.2.11 on 2024-04-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_loginhistory_managers_loginhistory_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-id',), 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها'},
        ),
    ]
