# Generated by Django 4.2.11 on 2024-04-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_image',
        ),
    ]
