# Generated by Django 4.2.11 on 2024-04-21 18:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_authority_option_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_card_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_file_path_for_birth, verbose_name='تصویر شناسنامه'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_card_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_file_path_for_national, verbose_name='تصویر کارت ملی'),
        ),
    ]
