# Generated by Django 4.2.11 on 2024-04-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_birth_card_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_matched_national_code',
            field=models.BooleanField(default=False),
        ),
    ]
