# Generated by Django 4.2.11 on 2024-04-23 18:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_mobile_matched_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default=users.models._generate_referral_code, max_length=8),
        ),
    ]
