# Generated by Django 4.2.11 on 2024-04-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ('-id',), 'verbose_name': 'Login history', 'verbose_name_plural': 'Login histories'},
        ),
    ]
