# Generated by Django 4.2.11 on 2024-04-09 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitpin', '0015_alter_bitpincurrency_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('value', 'Value'), ('percent', 'Percent')], default='value', verbose_name='Commission Type')),
                ('amount', models.FloatField(default=0, verbose_name='Commission Amount')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitpin.bitpincurrency')),
                ('network_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitpin.bitpinnetwork')),
            ],
            options={
                'verbose_name': 'Withdraw Commission',
                'verbose_name_plural': 'Withdraw Commissions',
            },
        ),
    ]
