# Generated by Django 4.2.11 on 2024-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='withdrawcommission',
            constraint=models.UniqueConstraint(fields=('currency_id', 'network_id'), name='currency_network_id'),
        ),
    ]
