# Generated by Django 4.2.11 on 2024-04-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_withdrawcommission_currency_network_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='withdrawcommission',
            name='currency_network_id',
        ),
        migrations.AddConstraint(
            model_name='withdrawcommission',
            constraint=models.UniqueConstraint(fields=('currency_id', 'network_id'), name='currency_network_id', violation_error_message='test'),
        ),
    ]
