# Generated by Django 4.2.11 on 2024-04-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0003_remove_withdrawcommission_currency_network_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='withdrawcommission',
            name='currency_network_id',
        ),
        migrations.AddConstraint(
            model_name='withdrawcommission',
            constraint=models.UniqueConstraint(fields=('currency_id', 'network_id'), name='currency_network_id'),
        ),
    ]
