# Generated by Django 4.2.11 on 2024-04-22 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JibitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('national_with_mobile', 'Check national code with mobile number'), ('national_with_creditcard', 'Check national code with credit card number')], max_length=24)),
                ('result_json', models.JSONField()),
                ('matched', models.BooleanField(default=False)),
                ('successful_request', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jibit Reqeust',
                'verbose_name_plural': 'Jibit Requests',
            },
        ),
    ]
