# Generated by Django 4.2.11 on 2024-04-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jibitconfiguration',
            name='last_call_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jibitconfiguration',
            name='token',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
