# Generated by Django 4.2.11 on 2024-04-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_jibitconfiguration_last_call_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jibitconfiguration',
            name='refresh',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
