# Generated by Django 4.2.8 on 2023-12-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='type',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('reset', 'Reset Password')], default='login', max_length=20, verbose_name='نوع کدتایید'),
        ),
    ]
