# Generated by Django 4.2.11 on 2024-04-18 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_alter_otp_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='otp',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='write_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.IntegerField(verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='type',
            field=models.CharField(choices=[('login', 'ورود'), ('register', 'ثبت نام'), ('transaction', 'ایجاد تراکنش'), ('transfer', 'Transfer'), ('reset_password', 'بازیابی رمزعبور'), ('forget_password', 'FORGET Password')], default='login', max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
