# Generated by Django 4.2.11 on 2024-04-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_otp_created_at_remove_otp_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='type',
            field=models.CharField(choices=[('login', 'ورود'), ('withdraw', 'برداشت'), ('transfer', 'Transfer'), ('reset_password', 'بازیابی رمزعبور'), ('forget_password', 'Forget Password')], default='login', max_length=20),
        ),
    ]
