# Generated by Django 4.2.11 on 2024-04-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=11, default=0.0, max_digits=24, verbose_name='موجودی'),
        ),
    ]
