# Generated by Django 4.2.11 on 2024-04-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18, verbose_name='موجودی'),
        ),
    ]
