# Generated by Django 4.2.11 on 2024-04-27 14:33

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=api.models.RoundedDecimalField(decimal_places=5, default=0.0, max_digits=18, verbose_name='موجودی'),
        ),
    ]
