# Generated by Django 4.2.11 on 2024-04-04 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RialWithdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Amount')),
                ('factor_number', models.CharField(unique=True, verbose_name='Factor number')),
                ('sheba_number', models.CharField(max_length=26, verbose_name='Sheba Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('cancel', 'Cancel')], default='pending', max_length=7, verbose_name='Status')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rial withdraw',
                'verbose_name_plural': 'Rial withdraws',
                'ordering': ('-id',),
            },
        ),
    ]
