# Generated by Django 4.2.11 on 2024-04-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0002_rialwithdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='rialwithdraw',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
