# Generated by Django 4.2.11 on 2024-04-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0003_rialwithdraw_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rialdeposit',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='rialdeposit',
            name='factor_number',
            field=models.CharField(unique=True, verbose_name='شماره فاکتور'),
        ),
        migrations.AlterField(
            model_name='rialdeposit',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('success', 'Success'), ('cancel', 'لغو')], default='pending', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rialwithdraw',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='rialwithdraw',
            name='factor_number',
            field=models.CharField(unique=True, verbose_name='شماره فاکتور'),
        ),
        migrations.AlterField(
            model_name='rialwithdraw',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('success', 'Success'), ('cancel', 'لغو')], default='pending', max_length=7, verbose_name='Status'),
        ),
    ]
