# Generated by Django 4.2.11 on 2024-04-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0004_alter_rialdeposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rialdeposit',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=11, verbose_name='مقدار'),
        ),
    ]
