# Generated by Django 4.2.8 on 2024-01-22 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityRuleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(verbose_name='title')),
                ('field_key', models.CharField(verbose_name='field key')),
                ('type', models.CharField(choices=[('range', 'Range'), ('defined', 'Defined')], verbose_name='type')),
                ('is_form', models.BooleanField(default=False, verbose_name='Is form')),
                ('min_value', models.IntegerField(verbose_name='min value')),
                ('max_value', models.IntegerField(verbose_name='max value')),
                ('process_time', models.CharField(help_text='1 Day, 2 Hours, ...', verbose_name='َApproximate processing time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(verbose_name='title')),
                ('deposit_ir_limit', models.IntegerField(verbose_name='daily Rial deposit limit')),
                ('deposit_ir_limit_text', models.CharField(verbose_name='daily Rial deposit limit description')),
                ('withdraw_ir_limit', models.IntegerField(verbose_name='daily Rial withdraw limit')),
                ('withdraw_ir_limit_text', models.CharField(verbose_name='daily Rial withdraw limit description')),
                ('deposit_crypto_limit', models.IntegerField(verbose_name='daily Crypto deposit limit')),
                ('deposit_crypto_limit_text', models.CharField(verbose_name='daily Crypto deposit limit description')),
                ('withdraw_crypto_limit', models.IntegerField(verbose_name='daily Crypto withdraw limit')),
                ('withdraw_crypto_limit_text', models.CharField(verbose_name='daily Crypto withdraw limit description')),
                ('option_ids', models.ManyToManyField(to='authority.authorityruleoption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField()),
                ('admin_message', models.CharField(verbose_name='Admin message')),
                ('AuthorityRule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authority.authorityrule', verbose_name='Rule ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requesting user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
