# Generated by Django 4.2.8 on 2024-01-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorityrequest',
            options={'verbose_name': 'Authority request', 'verbose_name_plural': 'Authority requests'},
        ),
        migrations.AlterModelOptions(
            name='authorityrule',
            options={'verbose_name': 'Authority rule', 'verbose_name_plural': 'Authority rules'},
        ),
        migrations.AlterModelOptions(
            name='authorityruleoption',
            options={'verbose_name': 'Authority rule option', 'verbose_name_plural': 'Authority rule options'},
        ),
        migrations.RenameField(
            model_name='authorityrequest',
            old_name='AuthorityRule',
            new_name='rule_id',
        ),
        migrations.AlterField(
            model_name='authorityrequest',
            name='admin_message',
            field=models.CharField(blank=True, verbose_name='Admin message'),
        ),
        migrations.AlterField(
            model_name='authorityruleoption',
            name='max_value',
            field=models.IntegerField(blank=True, verbose_name='max value'),
        ),
        migrations.AlterField(
            model_name='authorityruleoption',
            name='min_value',
            field=models.IntegerField(blank=True, verbose_name='min value'),
        ),
        migrations.AlterField(
            model_name='authorityruleoption',
            name='process_time',
            field=models.CharField(blank=True, help_text='1 Day, 2 Hours, ...', verbose_name='َApproximate processing time'),
        ),
        migrations.CreateModel(
            name='AuthorityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(verbose_name='Level')),
                ('rule_ids', models.ManyToManyField(to='authority.authorityrule')),
            ],
            options={
                'ordering': ('level',),
            },
        ),
    ]
