# Generated by Django 4.2.8 on 2024-01-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0003_alter_authorityrequest_admin_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorityrule',
            name='deposit_crypto_limit',
        ),
        migrations.RemoveField(
            model_name='authorityrule',
            name='deposit_crypto_limit_text',
        ),
        migrations.RemoveField(
            model_name='authorityrule',
            name='deposit_ir_limit',
        ),
        migrations.RemoveField(
            model_name='authorityrule',
            name='deposit_ir_limit_text',
        ),
        migrations.RemoveField(
            model_name='authorityrule',
            name='withdraw_crypto_limit',
        ),
        migrations.RemoveField(
            model_name='authorityrule',
            name='withdraw_crypto_limit_text',
        ),
        migrations.RemoveField(
            model_name='authorityrule',
            name='withdraw_ir_limit',
        ),
        migrations.RemoveField(
            model_name='authorityrule',
            name='withdraw_ir_limit_text',
        ),
        migrations.AddField(
            model_name='authoritylevel',
            name='deposit_crypto_limit',
            field=models.IntegerField(default=0, verbose_name='daily Crypto deposit limit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authoritylevel',
            name='deposit_crypto_limit_text',
            field=models.CharField(default=0, verbose_name='daily Crypto deposit limit description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authoritylevel',
            name='deposit_ir_limit',
            field=models.IntegerField(default=0, verbose_name='daily Rial deposit limit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authoritylevel',
            name='deposit_ir_limit_text',
            field=models.CharField(default=0, verbose_name='daily Rial deposit limit description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authoritylevel',
            name='withdraw_crypto_limit',
            field=models.IntegerField(default=0, verbose_name='daily Crypto withdraw limit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authoritylevel',
            name='withdraw_crypto_limit_text',
            field=models.CharField(default=0, verbose_name='daily Crypto withdraw limit description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authoritylevel',
            name='withdraw_ir_limit',
            field=models.IntegerField(default=0, verbose_name='daily Rial withdraw limit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authoritylevel',
            name='withdraw_ir_limit_text',
            field=models.CharField(default=0, verbose_name='daily Rial withdraw limit description'),
            preserve_default=False,
        ),
    ]
