# Generated by Django 4.2.8 on 2024-01-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0004_remove_authorityrule_deposit_crypto_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorityrule',
            options={'ordering': ('sequence',), 'verbose_name': 'Authority rule', 'verbose_name_plural': 'Authority rules'},
        ),
        migrations.AddField(
            model_name='authorityrule',
            name='sequence',
            field=models.IntegerField(default=1, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='authorityruleoption',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image'), ('boolean', 'boolean')], default='text', verbose_name='field type'),
            preserve_default=False,
        ),
    ]
