# Generated by Django 4.2.8 on 2024-01-26 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authority', '0005_alter_authorityrule_options_authorityrule_sequence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorityrequest',
            options={'verbose_name': 'درخواست احراز هویت', 'verbose_name_plural': 'درخواست های احراز هویت'},
        ),
        migrations.AlterModelOptions(
            name='authorityrule',
            options={'ordering': ('sequence',), 'verbose_name': 'قانون احراز هویت', 'verbose_name_plural': 'قوانین احراز هویت'},
        ),
        migrations.AlterModelOptions(
            name='authorityruleoption',
            options={'verbose_name': 'فیلد قانون احراز هویت', 'verbose_name_plural': 'فیلدهای قانون احراز هویت'},
        ),
        migrations.AlterField(
            model_name='authoritylevel',
            name='deposit_crypto_limit',
            field=models.IntegerField(verbose_name='محدودیت واریز رمزارز روزانه'),
        ),
        migrations.AlterField(
            model_name='authoritylevel',
            name='deposit_crypto_limit_text',
            field=models.CharField(verbose_name=' توضیح محدودیت واریز رمزارز روزانه'),
        ),
        migrations.AlterField(
            model_name='authoritylevel',
            name='deposit_ir_limit',
            field=models.IntegerField(verbose_name='محدودیت واریز ریالی روزانه'),
        ),
        migrations.AlterField(
            model_name='authoritylevel',
            name='deposit_ir_limit_text',
            field=models.CharField(verbose_name='توضیح محدودیت واریز ریالی روزانه'),
        ),
        migrations.AlterField(
            model_name='authoritylevel',
            name='level',
            field=models.CharField(verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='authoritylevel',
            name='withdraw_crypto_limit',
            field=models.IntegerField(verbose_name='محدودیت برداشت رمزارز روزانه'),
        ),
        migrations.AlterField(
            model_name='authoritylevel',
            name='withdraw_crypto_limit_text',
            field=models.CharField(verbose_name='توضیح محدودیت برداشت رمزارز روزانه'),
        ),
        migrations.AlterField(
            model_name='authoritylevel',
            name='withdraw_ir_limit',
            field=models.IntegerField(verbose_name='محدودیت برداشت ریالی روزانه'),
        ),
        migrations.AlterField(
            model_name='authoritylevel',
            name='withdraw_ir_limit_text',
            field=models.CharField(verbose_name='توضیح محدودیت برداشت ریالی روزانه'),
        ),
        migrations.AlterField(
            model_name='authorityrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authorityrequest',
            name='rule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authority.authorityrule', verbose_name='شناسه قانون احراز هویت'),
        ),
        migrations.AlterField(
            model_name='authorityrequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست کننده'),
        ),
        migrations.AlterField(
            model_name='authorityrule',
            name='sequence',
            field=models.IntegerField(default=1, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='authorityrule',
            name='title',
            field=models.CharField(verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='authorityruleoption',
            name='field_key',
            field=models.CharField(verbose_name='کلید فیلد'),
        ),
        migrations.AlterField(
            model_name='authorityruleoption',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image'), ('boolean', 'boolean')], verbose_name='نوع فیلد'),
        ),
        migrations.AlterField(
            model_name='authorityruleoption',
            name='is_form',
            field=models.BooleanField(default=False, verbose_name='در وبسایت نمایش داده شود'),
        ),
        migrations.AlterField(
            model_name='authorityruleoption',
            name='max_value',
            field=models.IntegerField(blank=True, verbose_name='حداکثر'),
        ),
        migrations.AlterField(
            model_name='authorityruleoption',
            name='min_value',
            field=models.IntegerField(blank=True, verbose_name='حداقل'),
        ),
        migrations.AlterField(
            model_name='authorityruleoption',
            name='process_time',
            field=models.CharField(blank=True, help_text='۱روز ،\u200c ۲ساعت ...', verbose_name='َApproximate processing time'),
        ),
        migrations.AlterField(
            model_name='authorityruleoption',
            name='title',
            field=models.CharField(verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='authorityruleoption',
            name='type',
            field=models.CharField(choices=[('range', 'رنج'), ('defined', 'تعریف شده یا نشده')], verbose_name='نوع'),
        ),
    ]
