# Generated by Django 4.2.11 on 2024-04-05 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bitpin', '0012_bitpincurrency_show_in_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=8, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Amount')),
                ('wallet_address', models.CharField(max_length=255, verbose_name='Wallet Address')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('cancel', 'Cancel'), ('reject', 'REJECT')], default='pending', max_length=10)),
                ('tx_id', models.CharField(max_length=255, verbose_name='Transaction ID')),
                ('submit_date', models.DateTimeField(blank=True, null=True, verbose_name='Submit Date')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bitpin.bitpincurrency', verbose_name='Currency')),
                ('network_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bitpin.bitpinnetwork', verbose_name='Network')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Crypto Transaction',
                'verbose_name_plural': 'Crypto Transactions',
                'ordering': ('-id',),
            },
        ),
    ]
