# Generated by Django 4.2.8 on 2024-04-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wallet ID'),
        ),
    ]
