# Generated by Django 4.2.11 on 2024-04-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency_current_value',
            field=models.PositiveBigIntegerField(default=0, verbose_name='The irt price at the time of placing the ordering.'),
        ),
    ]
