# Generated by Django 4.2.11 on 2024-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='factor_number',
            field=models.CharField(default='QQ', max_length=255, verbose_name='Factor Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='factor_number',
            field=models.CharField(default='q', max_length=255, verbose_name='Factor Number'),
            preserve_default=False,
        ),
    ]
