# Generated by Django 4.2.11 on 2024-04-09 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0015_alter_bitpincurrency_options_and_more'),
        ('order', '0004_order_factor_number_transaction_factor_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency_current_value',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت تومان در زمان ثبت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='factor_number',
            field=models.CharField(max_length=255, verbose_name='شماره فاکتور'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('approve', 'تایید'), ('cancel', 'لغو'), ('reject', 'REJECT')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('buy', 'خرید'), ('sell', 'فروش')], max_length=8, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_current_value',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت تومان در زمان ثبت سفارش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bitpin.bitpincurrency', verbose_name='ارز'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='factor_number',
            field=models.CharField(max_length=255, verbose_name='شماره فاکتور'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='network_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bitpin.bitpinnetwork', verbose_name='شبکه'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('approve', 'تایید'), ('cancel', 'لغو'), ('reject', 'رد')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت')], max_length=8, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(max_length=255, verbose_name='آدرس کیف پول'),
        ),
    ]
