# Generated by Django 4.2.11 on 2024-04-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_options_alter_order_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-submit_date', '-create_date'), 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-submit_date', '-create_date'), 'verbose_name': 'Crypto Transaction', 'verbose_name_plural': 'Crypto Transactions'},
        ),
    ]
