# Generated by Django 4.2.11 on 2024-04-17 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0016_bitpincurrency_markup_percent_bitpincurrency_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_alter_order_options_alter_transaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('successful', models.BooleanField()),
                ('destination_mobile', models.CharField(max_length=11)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bitpin.bitpincurrency')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ('-create_date',),
            },
        ),
    ]
