# Generated by Django 4.2.11 on 2024-04-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_after_commission',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Amount after commission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='applied_commission_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Commission in request time'),
            preserve_default=False,
        ),
    ]
