# Generated by Django 4.2.11 on 2024-04-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_transaction_amount_after_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_after_commission',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Amount after commission'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='applied_commission_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Commission in request time'),
        ),
    ]
