# Generated by Django 4.2.11 on 2024-04-19 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitpin', '0019_bitpincurrency_price_usdt'),
        ('order', '0010_alter_order_amount_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='base_currency_id',
            field=models.ForeignKey(default=3335, on_delete=django.db.models.deletion.RESTRICT, related_name='usdt_order_set', to='bitpin.bitpincurrency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=9, max_digits=20, verbose_name='مقدار'),
        ),
    ]
