# Generated by Django 4.2.11 on 2024-04-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_base_currency_id_alter_transfer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency_currency_usdt_value',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=20, verbose_name='USDT price at the time of placing the order.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency_current_value',
            field=models.PositiveBigIntegerField(default=0, verbose_name='The irt price at the time of placing the order.'),
        ),
    ]
